import test from 'node:test';
import assert from 'node:assert/strict';
import { createServer } from 'node:http';
import { JobFacts } from '../src/job-facts.mjs';

test('job facts use the configured API key, cache requests, bound ignored Range responses and validate thumbnails', async t => {
 const requests = [], png = Buffer.from([137,80,78,71,13,10,26,10,0,0]);
 let relative = '.thumbs/model.png';
 const server = createServer((req,res) => {
  requests.push({ path:req.url, key:req.headers['x-api-key'], range:req.headers.range });
  if(req.url.startsWith('/server/files/metadata')) res.end(JSON.stringify({ result:{ object_height:24, slicer:'Fixture', thumbnails:[{width:512,relative_path:relative}] } }));
  else if(req.url.endsWith('.png'))res.end(png);
  else res.end('; generated by Fixture\n'+'a'.repeat(100000));
 });
 await new Promise(r=>server.listen(0,'127.0.0.1',r)); t.after(()=>{server.closeAllConnections();server.close();});
 const state={configurationId:'config-1',job:{id:'job-1',filename:'folder/model.gcode'}};
 const p={config:{moonraker:`http://127.0.0.1:${server.address().port}`,apiKey:'fixture'},snapshot:()=>state};
 const facts=new JobFacts({telemetry:new Map([['one',p]])});
 const value=await facts.get('one'); assert.equal(value.header.length,24576); assert.equal(value.result.object_height,24); assert.match(value.preview,/^data:image\/png;base64,/);
 assert.ok(requests.every(r=>r.key==='fixture')); assert.equal(requests[1].range,'bytes=0-24575'); assert.ok(requests.some(r=>r.path==='/server/files/gcodes/folder/.thumbs/model.png'));
 await facts.get('one'); assert.equal(requests.length,3);
 relative='../../outside.png'; state.job.id='job-2'; const rejected=await facts.get('one'); assert.equal(rejected.preview,null); assert.equal(requests.length,5);
 state.job.filename='../secret'; const unsafe=await facts.get('one'); assert.equal(unsafe.header,''); assert.equal(requests.length,5);
});
test('job facts bound in-flight work and reject a result after printer retargeting', async () => {
 const telemetry=new Map(['one','two'].map(id=>[id,{config:{},snapshot:()=>({configurationId:id,job:{id:'job',filename:'model.gcode'}})}]));
 const facts=new JobFacts({telemetry,limit:1}); let release; facts.load=()=>new Promise(r=>{release=r;});
 const work=facts.get('one'); await assert.rejects(facts.get('two'),/busy/);
 telemetry.set('one',{...telemetry.get('one')}); release({filename:'model.gcode'}); await assert.rejects(work,/changed/); assert.equal(facts.pending.size,0); assert.equal(facts.cache.size,0);
});
