import { demoFetch as fetch } from './demo-api.js';
import { ControlClient, sourceState, requestId } from './ui-core.js';
import { CameraPool } from './camera.js';
import { loadSpools } from './color-library.js';
import { ColorLibraryView } from './color-library-view.js';

const $ = selector => document.querySelector(selector);
function node(tag, className, text) { const n = document.createElement(tag); if (className) n.className = className; if (text != null) n.textContent = text; return n; }
function button(text, click, className = '') { const b = node('button', className, text); b.type = 'button'; b.addEventListener('click', click); return b; }
function link(text, href) { const a = node('a', '', text); a.href = href; a.target = '_blank'; a.rel = 'noreferrer'; return a; }
const duration = seconds => Number.isFinite(seconds) ? `${Math.floor(seconds / 3600)}h ${Math.floor(seconds % 3600 / 60)}m` : '—';
const time = at => Number.isFinite(at) ? new Date(at).toLocaleString([], { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' }) : '—';
const words = value => (value ?? 'unknown').replaceAll('_', ' ');
const jobLabel = filename => filename ? filename.replace(/\.gcode$/i, '').replaceAll('_', ' ') : 'No job reported';
const COUNT_KEY = 'print-room.printer-count';
const origin = (url, host, port) => (url || (host ? `http://${host}:${port}` : '')).replace(/\/$/, '');
const fluiddOrigin = p => p.links ? (p.links.fluidd ?? '').replace(/\/$/, '') : origin(null, p.host, 4408);
const measure = value => Number.isInteger(value) ? String(value) : String(Math.round(value * 10) / 10);
const rememberedPrinters = () => {
  try {
    const n = Number(disk?.getItem?.(COUNT_KEY));
    if (Number.isInteger(n) && n >= 1 && n <= 64) return n;
  } catch { /* private mode */ }
  return 1;
};
const rememberPrinters = n => { try { disk.setItem(COUNT_KEY, String(n)); } catch { /* private mode */ } };
const sourceFresh = (source, now) => source && sourceState(source, now) === 'fresh';
const printerLive = (p, now) => sourceFresh(p.sources.moonraker, now) || sourceFresh(p.sources.vendor, now);
function gcodePreview(text) {
  let best = null;
  for (const m of text.matchAll(/; thumbnail begin (\d+)x(\d+) \d+\r?\n([\s\S]*?); thumbnail end/g)) {
    const area = Number(m[1]) * Number(m[2]);
    const b64 = m[3].replace(/^; ?/gm, '').replace(/\s+/g, '');
    if (b64 && (!best || area > best.area)) best = { area, b64 };
  }
  return best ? `data:image/png;base64,${best.b64}` : '';
}
function loadJobFacts(card, printer, filename) {
  if (card.metaKey === (filename ?? '') || card.metaRetryAt > Date.now()) return;
  card.metaKey = filename ?? '';
  card.usedAt = 0;
  card.objectMeta.textContent = '';
  card.preview.hidden = true;
  card.preview.removeAttribute('src');
  card.preview.dataset.thumbs = '';
  if (!filename) return;
  api(`/api/v1/printers/${encodeURIComponent(printer.id)}/job-facts`).then(data => {
    const head = data.header ?? '';
    if (card.metaKey !== filename) return;
    const meta = data.result ?? {};
    const tall = Number.isFinite(meta.object_height) ? meta.object_height : Number((head.match(/; max_z_height:\s*([\d.]+)/) || [])[1]);
    const layers = Number((head.match(/; total layer number:\s*(\d+)/) || [])[1]);
    const bits = [];
    if (Number.isFinite(tall)) bits.push(`${measure(tall)} mm tall`);
    if (Number.isFinite(meta.layer_height)) bits.push(`${measure(meta.layer_height)} mm layers`);
    else if (Number.isFinite(meta.first_layer_height)) bits.push(`${measure(meta.first_layer_height)} mm first layer`);
    if (Number.isFinite(layers)) bits.push(`${layers} layers`);
    if (Number.isFinite(meta.nozzle_diameter)) bits.push(`${measure(meta.nozzle_diameter)} mm nozzle`);
    const minx = Number((head.match(/; MINX\s*=\s*([-\d.]+)/i) || [])[1]);
    const maxx = Number((head.match(/; MAXX\s*=\s*([-\d.]+)/i) || [])[1]);
    const miny = Number((head.match(/; MINY\s*=\s*([-\d.]+)/i) || [])[1]);
    const maxy = Number((head.match(/; MAXY\s*=\s*([-\d.]+)/i) || [])[1]);
    if ([minx, maxx, miny, maxy].every(Number.isFinite)) bits.push(`${measure(maxx - minx)} × ${measure(maxy - miny)} mm on bed`);
    const ftype = meta.filament_type || (head.match(/; filament_types?\s*[:=]\s*([^\r\n]+)/i) || [])[1];
    if (ftype) bits.push([...new Set(String(ftype).split(/[,;]/).map(s => s.trim()).filter(Boolean))].join(', '));
    if (Number.isFinite(meta.filament_total)) bits.push(`${measure(meta.filament_total / 1000)} m estimated`);
    if (Number.isFinite(meta.filament_weight_total)) bits.push(`${measure(meta.filament_weight_total)} g filament`);
    if (Number.isFinite(meta.size)) bits.push(`${(meta.size / 1_000_000).toFixed(1)} MB`);
    const generated = (head.match(/; generated by ([^\r\n]+)/) || [])[1];
    const slicer = generated || (meta.slicer && meta.slicer !== 'Unknown' ? [meta.slicer, meta.slicer_version].filter(Boolean).join(' ') : '');
    if (slicer) bits.push(String(slicer).replace(/\s+on .*/, ''));
    card.objectMeta.textContent = bits.join(' · ');
    const src = gcodePreview(head);
    if (src) { card.preview.src = src; return; }
    if (data.preview) card.preview.src = data.preview;
  }).catch(() => { if (card.metaKey === filename) { card.metaKey = null; card.metaRetryAt = Date.now() + 10000; } });
}
let session, sessionWork, fleet, fleetError, metadataError, actionError, imports = [], projects = [], spools = [], assignments = { version: 0, assignments: [] }, integration = {};
let cfsyncState=null,cfsyncError=null,inventoryObservedAt=null,inventoryError=null,inventoryRevision=null;
const libraryView=new ColorLibraryView($('#colors'));
const currentAssignments=()=>integration.cfsyncConfigured?(cfsyncState?.assignments??[]):assignments.assignments;
const cards = new Map(); const stops = new Map(); const cameraPool = new CameraPool({ limit: 4 });
let pairingRequired = false;
function showPairing(message) {
  session = null; pairingRequired = true; fleet = null;
  $('#pairing').hidden = false; $('#workspace').hidden = true; $('.stop-strip').hidden = true;
  $('#connection').textContent = 'Pairing required'; $('#connection').dataset.state = 'offline';
  $('#pairing-error').textContent = message;
  if ($('#editor').open) $('#editor').close();
  for (const c of cards.values()) c.camera.close(); cards.clear(); $('#printer-grid').replaceChildren();
}
async function browserSession(code) {
  if (!sessionWork) sessionWork = (async () => {
    const r = await fetch('/api/session', { method: 'POST', credentials: 'same-origin', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(code ? { code } : {}), signal: AbortSignal.timeout(5000) });
    const data = await r.json();
    if (!r.ok) {
      if (data.pairingRequired) showPairing(code ? data.error : '');
      throw new Error(data.error ?? 'Could not connect to Print room');
    }
    session = data; pairingRequired = false;
    $('#pairing').hidden = true; $('#workspace').hidden = false; $('.stop-strip').hidden = false;
    requestAnimationFrame(spyNav);
    $('#pair-device').hidden = session.access !== 'localhost' || !session.lanUrl || !session.pairingRequired;

    return session;
  })().finally(() => { sessionWork = null; });
  return sessionWork;
}
async function api(path, body, renewed = false) {
  if (!session || session.expiresAt < Date.now() + 10000) await browserSession();
  const r = await fetch(path, { method: body === undefined ? 'GET' : 'POST', credentials: 'same-origin', cache: 'no-store',
    headers: body === undefined ? {} : { 'Content-Type': 'application/json', 'X-Print-CSRF': session.csrf },
    body: body === undefined ? undefined : JSON.stringify(body), signal: AbortSignal.timeout(path.includes('/cameras/') ? 12000 : 10000) });
  if (r.status === 401 && body === undefined && !renewed) { await browserSession(); return api(path, undefined, true); }
  if (r.status === 401 && session?.access === 'lan' && session.pairingRequired) showPairing('Access expired. Enter a new pairing code from the Print room host.');
  const data = await r.json();
  if (!r.ok) { const e = new Error(data.error ?? `Request failed (${r.status})`); e.status = r.status; throw e; }
  return data;
}
let disk;
try { disk = window.localStorage; } catch { disk = { getItem() { throw new Error('Storage unavailable'); }, setItem() { throw new Error('Storage unavailable'); } }; }
const controls = new ControlClient({ storage: disk, api });
function toast(message) { $('#toast').textContent = message; $('#toast').hidden = false; clearTimeout(toast.timer); toast.timer = setTimeout(() => $('#toast').hidden = true, 7000); }
function showSkeletons(count = rememberedPrinters()) {
  if (cards.size) return;
  const grid = $('#printer-grid');
  if (grid.querySelectorAll('.skeleton').length !== count) {
    grid.replaceChildren();
    for (let i = 0; i < count; i++) {
      const card = node('article', 'printer skeleton');
      card.setAttribute('aria-hidden', 'true');
      card.innerHTML = '<div class="printer-head"><div><h2 class="skel-line"></h2></div><span class="badge skel-line"></span></div><div class="camera skel-camera"></div><div class="printer-body"><div class="skel-line"></div><div class="slots"><div class="slot skel-slot"></div><div class="slot skel-slot"></div><div class="slot skel-slot"></div><div class="slot skel-slot"></div></div></div>';
      grid.append(card);
    }
  }
}
function makeCard(p) {
  const grid = $('#printer-grid');
  if (grid.querySelector('.skeleton')) grid.replaceChildren();
  const root = node('article', 'printer'); root.setAttribute('aria-label', p.name); root.dataset.printer = p.id;
  root.style.setProperty('--i', String($('#printer-grid').children.length));
  const head = node('div', 'printer-head'), identity = node('div');
  identity.append(node('p', 'eyebrow', p.id.toUpperCase()), node('h2', '', p.name));
  const fluidd = fluiddOrigin(p);
  const address = fluidd ? link(p.host ? `${p.host} · Printer UI` : 'Open printer UI', fluidd) : node('span', '', p.host ?? '');
  address.className = 'printer-address'; identity.append(address);
  const phase = node('span', 'badge', 'Connecting'); head.append(identity, phase);
  const camera = node('div', 'camera'), video = node('video'); video.autoplay = true; video.muted = true; video.playsInline = true; video.controls = false;
  video.setAttribute('aria-label', `${p.name} live camera`);
  camera.dataset.configured = String(p.cameraConfigured !== false);
  const previewSide = Number(p.id.split('-').at(-1)) % 2 === 0 ? 'right' : 'left';
  const cameraPreview = node('img', 'demo-camera-preview');
  cameraPreview.src = './printer-' + previewSide + '.jpg';
  cameraPreview.alt = 'Static K2 Plus preview recreated from a real Printroom camera view';
  cameraPreview.loading = 'lazy'; cameraPreview.decoding = 'async';
  camera.append(cameraPreview); video.setAttribute('aria-hidden', 'true');
  const cameraStatus = node('div', 'camera-overlay', 'CONNECTING'), cameraHint = node('div', 'camera-hint');
  const expand = button('⛶', () => camera.requestFullscreen?.().catch(() => toast('Fullscreen is unavailable in this browser')), 'camera-expand'); expand.setAttribute('aria-label', `Expand ${p.name} camera`);
  expand.hidden = p.cameraConfigured === false;
  const hud = node('div', 'camera-hud'), percentage = node('div', 'percentage');
  const progress = node('div', 'progress'), fill = node('div', 'progress-fill'); progress.append(fill); progress.setAttribute('role', 'progressbar'); progress.setAttribute('aria-label', `${p.name} job progress`); progress.setAttribute('aria-valuemin', '0'); progress.setAttribute('aria-valuemax', '100');
  const temperatures = node('div', 'temperatures'), temps = {};
  for (const [id, name] of [['nozzle', 'Nozzle'], ['bed', 'Bed'], ['chamber', 'Chamber']]) { const wrap = node('div', 'temperature'), current = node('strong'), target = node('small'); wrap.append(node('span', '', name), current, target); temperatures.append(wrap); temps[id] = { wrap, current, target }; }
  hud.append(percentage, progress, temperatures);
  camera.append(video, cameraStatus, cameraHint, expand, hud);
  const body = node('div', 'printer-body');
  const more = node('details', 'job-more');
  const summary = node('summary', '', 'More details');
  const preview = node('img', 'job-preview'); preview.alt = `${p.name} Fluidd job preview`; preview.hidden = true;
  preview.addEventListener('error', () => {
    const next = (preview.dataset.thumbs ?? '').split('\n').filter(Boolean);
    if (next.length) { preview.src = next.shift(); preview.dataset.thumbs = next.join('\n'); return; }
    preview.hidden = true;
  });
  preview.addEventListener('load', () => { if (preview.naturalWidth > 8) preview.hidden = false; });
  const objectName = node('p', 'job-object');
  const objectMeta = node('p', 'job-object-meta');
  const filamentUsed = node('p', 'job-object-meta');
  const filename = node('div', 'filename');
  const details = node('div', 'job-details'), layers = node('span'), elapsed = node('span'), remaining = node('span'); details.append(layers, elapsed, remaining);
  const fluiddJob = link('Open printer job UI ↗', `${fluidd}/#/jobs`);
  more.append(summary, preview, objectName, objectMeta, filamentUsed, filename, details);
  if (fluidd) more.append(fluiddJob);
  const cfsMore = node('details', 'cfs-more');
  const cfsSummary = node('summary', ''); cfsSummary.append(node('span', 'cfs-label', 'CFS'), node('span', 'cfs-dots'));
  const cfs = node('div', 'cfs-stack'); cfsMore.append(cfsSummary, cfs);
  const sources = node('div', 'source-row'), sourceNodes = {};
  for (const [id, label] of [['moonraker', 'Motion'], ['vendor', 'Printer'], ['cfs', 'CFS']]) { const s = node('span'); sourceNodes[id] = { node: s, label }; sources.append(s); }
  const warning = node('p', 'printer-warning');
  body.append(more, cfsMore, sources, warning);
  const routine = node('div', 'printer-controls'), routineButtons = {};
  for (const action of ['pause', 'resume', 'cancel']) { const b = button(words(action), () => requestControl(p.id, action)); b.setAttribute('aria-label', `${words(action)} ${p.name}`); routineButtons[action] = b; routine.append(b); }
  if (fluidd) routine.append(link('Open printer UI ↗', fluidd)); root.append(head, camera, body, routine);
  $('#printer-grid').append(root);
  const card = { configurationId: p.configurationId, root, phase, filename, objectName, objectMeta, filamentUsed, preview, percentage, progress, fill, layers, elapsed, remaining, temps, cfs, cfsMore, cfsDots: cfsSummary.querySelector('.cfs-dots'), sources: sourceNodes, warning, routineButtons, cfsKey: null, metaKey: null };
  card.camera = cameraPool.attach({ video, container: camera, status: cameraStatus, hint: cameraHint, api, printerId: p.id, enabled: p.cameraConfigured !== false });
  cards.set(p.id, card); return card;
}
function updateCard(p) {
  const previous = cards.get(p.id);
  if (previous && previous.configurationId !== p.configurationId) { previous.camera.close(); previous.root.remove(); cards.delete(p.id); }
  const c = cards.get(p.id) ?? makeCard(p), now = Date.now();
  const stale = !printerLive(p, now);
  c.phase.textContent = stale ? `Last seen: ${words(p.phase)}` : words(p.phase); c.phase.dataset.state = stale ? 'stale' : p.phase;
  c.root.dataset.phase = stale ? 'stale' : p.phase;
  c.root.dataset.job = p.job.filename ? 'yes' : 'no';
  const slots = p.cfs.flatMap(b => b.slots);
  const activeSlot = slots.find(s => s.active && /^#[a-f0-9]{6}$/i.test(s.color ?? ''))
    ?? slots.find(s => /^#[a-f0-9]{6}$/i.test(s.color ?? ''));
  if (activeSlot) {
    const n = activeSlot.color.slice(1), r = parseInt(n.slice(0, 2), 16) / 255, g = parseInt(n.slice(2, 4), 16) / 255, b = parseInt(n.slice(4, 6), 16) / 255;
    const lum = 0.2126 * r + 0.7152 * g + 0.0722 * b;
    c.root.style.setProperty('--job-c', lum < 0.18 ? '#8a8074' : activeSlot.color);
    document.documentElement.style.setProperty(`--${p.id}-c`, activeSlot.color);
    const rank = fleet?.printers.findIndex(x => x.id === p.id) ?? -1;
    if (rank >= 0 && rank < 3) document.documentElement.style.setProperty(`--p${rank}-c`, activeSlot.color);
  } else {
    c.root.style.removeProperty('--job-c');
    document.documentElement.style.removeProperty(`--${p.id}-c`);
  }
  c.filename.textContent = p.job.filename ?? 'No job reported'; c.filename.title = p.job.filename ?? '';
  c.objectName.textContent = jobLabel(p.job.filename);
  loadJobFacts(c, p, p.job.filename);
  if (Number.isFinite(p.job.filamentUsedMm)) {
    c.filamentUsed.textContent = `${(p.job.filamentUsedMm / 1000).toFixed(1)} m extruded`;
  } else c.filamentUsed.textContent = '';
  const progress = p.phase === 'preparing' ? p.job.preparationPercent : p.job.progressPercent;
  c.percentage.textContent = Number.isFinite(progress) ? `${Math.round(progress)}%` : '—';
  c.fill.style.width = `${progress ?? 0}%`; if (progress == null) c.progress.removeAttribute('aria-valuenow'); else c.progress.setAttribute('aria-valuenow', progress);
  c.layers.textContent = p.phase === 'preparing' ? 'Preparing printer' : `Layer ${p.job.layer ?? '—'} / ${p.job.totalLayers ?? '—'}`;
  c.elapsed.textContent = `${duration(p.job.elapsedSeconds)} elapsed`; c.remaining.textContent = `${duration(p.job.remainingSeconds)} left (est.)`;
  for (const [id, t] of Object.entries(p.temperatures)) {
    const n = c.temps[id];
    n.current.textContent = t.current == null ? '—' : `${Math.round(t.current)}°`;
    n.target.textContent = t.target == null || (id === 'chamber' && t.target === 0) ? '' : `/ ${Math.round(t.target)}°`;
    n.wrap.dataset.stale = String(sourceState(t, now) !== 'fresh');
    n.wrap.hidden = t.current == null && t.target == null;
  }
  const cfsState = sourceState(p.sources.cfs, now), key = JSON.stringify([p.cfs, cfsState, assignments.version, cfsyncState?.version, cfsyncError]);
  if (key !== c.cfsKey) {
    c.cfsKey = key; c.cfs.replaceChildren(); c.cfsDots.replaceChildren();
    c.cfsMore.hidden = !p.cfs.length;
    for (const box of p.cfs) {
      const head = node('div', 'cfs-head', box.name); head.append(node('span', '', `${box.temperature ?? '—'}° · ${box.humidity ?? '—'}% humidity`));
      const slots = node('div', 'slots');
      for (const slot of box.slots) {
        const tile = node('div', 'slot'); tile.dataset.active = String(slot.active); tile.dataset.stale = String(cfsState !== 'fresh');
        const fill = node('div', 'slot-fill');
        const remain = slot.remainingPercent == null ? 0 : Math.max(0, Math.min(1, slot.remainingPercent / 100));
        tile.style.setProperty('--remain', String(remain));
        tile.dataset.remain = slot.remainingPercent == null ? 'unknown' : 'known';
        const top = node('div', 'slot-top'), swatch = node('span', 'swatch');
        if (/^#[a-f0-9]{6}$/i.test(slot.color ?? '')) {
          tile.style.setProperty('--slot-c', slot.color);
          tile.dataset.pigment = 'true';
          const n = slot.color.slice(1), r = parseInt(n.slice(0, 2), 16) / 255, g = parseInt(n.slice(2, 4), 16) / 255, b = parseInt(n.slice(4, 6), 16) / 255;
          const lum = 0.2126 * r + 0.7152 * g + 0.0722 * b;
          tile.style.setProperty('--slot-ink', lum < 0.45 ? '#f6f0e6' : '#1b1712');
          swatch.style.background = slot.color;
          if (slot.configuration === 'configured') {
            const dot = node('span', 'cfs-dot');
            dot.style.background = slot.color;
            dot.title = `${slot.designation}${slot.profile ? ` · ${slot.profile}` : ''}`;
            if (slot.active) dot.dataset.active = 'true';
            c.cfsDots.append(dot);
          }
        }
        top.append(swatch, node('span', '', slot.designation));
        tile.append(fill);
        const label = slot.configuration === 'configured' ? slot.profile || slot.material || 'Material unknown' : slot.configuration === 'unconfigured' ? 'Empty' : 'Unknown';
        tile.append(top, node('strong', '', label), node('small', '', slot.vendor ?? slot.profile ?? 'No material profile'));
        const amount = slot.remainingPercent == null ? '—' : `${slot.remainingPercent}%`;
        tile.append(node('small', slot.active ? 'active slot-remain' : 'slot-remain', `${slot.active ? 'In use · ' : ''}${amount}`));
        const mapped = currentAssignments().find(a => a.printerId === p.id && a.slot === slot.designation);
        if (mapped) { tile.append(node('small', 'slot-map', `Spool #${mapped.spoolId}`)); tile.title = mapped.source==='cfsync'?'Association from CFSync; '+mapped.state:`Operator confirmed ${time(mapped.confirmedAt)}. A manual physical move can invalidate this association.`; }
        else tile.title = slot.profile ?? `${slot.designation}: ${label}`;
        slots.append(tile);
      }
      c.cfs.append(head, slots);
    }
    if (!p.cfs.length) c.cfs.append(node('p', 'muted small', 'No connected CFS reported.'));
  }
  for (const [id, s] of Object.entries(c.sources)) {
    const source = p.sources[id];
    if (!source || (id !== 'moonraker' && source.observedAt == null && !source.error)) { s.node.hidden = true; continue; }
    s.node.hidden = false;
    const state = sourceState(source, now), age = source.observedAt == null ? null : Math.max(0, Math.floor((now - source.observedAt) / 1000));
    s.node.dataset.state = state; s.node.textContent = `${state === 'fresh' ? '●' : '○'} ${s.label} · ${age == null ? 'unavailable' : `${age}s`}`; s.node.title = source.error ?? `${s.label}: ${state}`;
  }
  const warnings = [...p.warnings];
  if (stale && !warnings.some(w => w.includes('outdated'))) warnings.push('Status is aging. Last values may be outdated.');
  if (controls.blocked(p.id)) warnings.unshift('A control request is pending or uncertain. Check Control activity before another routine command.');
  c.warning.textContent = warnings.join(' ');
  c.warning.title = warnings.join(' ');
  c.warning.hidden = stale || !warnings.length;
  for (const [action, b] of Object.entries(c.routineButtons)) b.disabled = !fleet?.controlsEnabled || stale || !p.controls[action] || controls.blocked(p.id) || controls.pending.has(`${p.id}:${action}`);
}
function renderFleet() {
  if (!fleet) return;
  rememberPrinters(fleet.printers.length);
  controls.printerIds = fleet.printers.map(p => p.id);
  const stopKey = `${fleet.printers.map(p => p.id).join()},all`;
  if ($('#stop-buttons').dataset.key !== stopKey) {
    $('#stop-buttons').dataset.key = stopKey;
    stops.clear();
    $('#stop-buttons').replaceChildren();
    for (const p of [...(fleet.printers.length <= 8 ? fleet.printers : []), { id: 'all', name: 'All printers' }]) {
      const short = p.id === 'all' ? 'Stop all' : `Stop ${p.name}`;
      const b = button(short, () => requestControl(p.id, 'emergency_stop')); b.setAttribute('aria-label', `Emergency stop ${p.name}`); stops.set(p.id, b); $('#stop-buttons').append(b);
    }
  }
  for (const [id, b] of stops) { b.disabled = !fleet.controlsEnabled || controls.pending.has(`${id}:emergency_stop`); b.title = fleet.controlsEnabled ? 'Immediately requests firmware shutdown; it does not switch off mains power.' : 'Printer controls are disabled in service configuration.'; }
  const keep = new Set(fleet.printers.map(p => p.id));
  for (const [id, c] of cards) if (!keep.has(id)) { c.camera.close(); cards.delete(id); c.root.remove(); }
  if (!fleet.printers.length) {
    $('#printer-grid').replaceChildren();
    const empty = node('p', 'empty', 'No enabled printers. '), settings = node('a', '', 'Add or enable a printer in Settings'); settings.href = './settings.html'; empty.append(settings); $('#printer-grid').append(empty);
  } else {
    $('#printer-grid').querySelector('.empty')?.remove();
    fleet.printers.forEach(updateCard);
    const query = $('#fleet-query').value.toLowerCase();
    for (const p of fleet.printers) cards.get(p.id).root.hidden = !`${p.name} ${p.id} ${p.host}`.toLowerCase().includes(query);
  }
  $('#fleet-filter').hidden = fleet.printers.length < 5 && !$('#fleet-query').value;
  const now = Date.now();
  const fresh = fleet.printers.filter(p => printerLive(p, now));
  const running = fresh.filter(p => ['printing', 'preparing', 'busy', 'paused'].includes(p.phase));
  $('#fleet-summary').textContent = `${running.length} active · ${fresh.length}/${fleet.printers.length} connected`;
  $('#room-mark').textContent = `${fleet.printers.length} printer${fleet.printers.length === 1 ? '' : 's'}`;
  $('#connection').textContent = fleetError ? 'Service unavailable' : session?.access === 'lan' ? 'Simulated data' : 'Simulated data'; $('#connection').dataset.state = fleetError ? 'offline' : 'online';
  const message = fleetError ? `${fleetError} Last values are retained and continue to age.` : !fleet.controlsEnabled ? 'Live monitoring · Printer controls are currently disabled in the service configuration.' : 'Live monitoring · Emergency buttons request immediate firmware shutdown. Each printer reports its own outcome.';
  $('#service-message').textContent = message; $('#service-message').dataset.warning = String(!!fleetError);
}
async function requestControl(target, action) {
  const expectedJobId = action === 'cancel' ? fleet.printers.find(p => p.id === target)?.job.id : undefined;
  const perform = async () => {
    try {
      const pending = controls.send(target, action, expectedJobId); renderActions(); renderFleet();
      await pending; renderActions(); renderFleet();
      document.getElementById('action-message').textContent = 'Request saved. Check the separate outcome for each printer below.';
    } catch (e) { toast(e.message); }
  };
  if (action === 'cancel') {
    const p = fleet.printers.find(p => p.id === target);
    openEditor(`Cancel ${p.name} job`, 'Cancel print', [node('p', 'dialog-note', `Cancel ${p.job.filename ?? 'the current job'}? This ends the print and cannot be undone.`)], async () => { closeEditor(); await perform(); });
  } else await perform();
}
const outcomes = { requested: 'Saved · dispatching', acknowledged: 'Printer acknowledged · awaiting state', shutdown_observed: 'Firmware shutdown observed', state_observed: 'Expected printer state observed', outcome_unknown: 'Outcome unknown · check printer', failed: 'Printer rejected request', operator_resolved: 'Operator resolved · physical check recorded' };
function renderActions() {
  const list = $('#action-list');
  const records = controls.records();
  const key = JSON.stringify([records, actionError, controls.storageWarning]);
  if (list.dataset.key === key) return;
  list.dataset.key = key; list.replaceChildren();
  if (!records.length) list.append(node('p', 'empty', 'No control requests recorded.'));
  for (const r of records.slice(0, 50)) {
    const row = node('article', 'action'), head = node('div', 'action-head'); head.append(node('strong', '', `${words(r.action)} · ${r.target === 'all' ? 'all printers' : r.target}`), node('span', 'muted small', time(r.createdAt)));
    row.append(head, node('div', 'action-id', `Request ${r.id}`));
    if (r.server) for (const t of r.server.targets) {
      const result = node('div', 'action-result', `${t.printerId}: ${outcomes[t.status] ?? words(t.status)}`); result.dataset.state = t.status;
      result.append(node('small', '', t.resolutionNote ?? t.detail ?? 'Waiting for printer response.')); row.append(result);
      if (t.status === 'outcome_unknown') row.append(button(`Record physical check · ${t.printerId}`, () => resolveAction(r, t.printerId)));
    } else {
      const result = node('div', 'action-result', `${words(r.transport)}${r.error ? ` · ${r.error}` : ''}`); result.dataset.state = r.transport; row.append(result);
      if (r.transport === 'outcome_unknown') row.append(button('Record physical check for missing request', () => resolveAction(r, r.target)));
    }
    list.append(row);
  }
  $('#action-message').textContent = actionError ? `Activity refresh failed: ${actionError}. Saved IDs are kept; nothing is resent.` : controls.storageWarning ?? 'A saved request or HTTP acknowledgment does not prove the printer stopped. Look for an observed state or record a physical check.';
  $('#action-message').dataset.warning = String(!!actionError || !!controls.storageWarning);
}
function resolveAction(record, printerId) {
  const note = field('What did you physically check?', 'note', { textarea: true, required: true, minLength: 10, maxLength: 1000 });
  const confirm = checkbox('I checked the printer and pending-command state. This records my observation; it does not verify the original request automatically.');
  openEditor(`Resolve ${printerId} outcome`, 'Record physical check', [note.wrap, confirm.wrap], async () => {
    if (!confirm.input.checked) throw new Error('Confirm your physical check first.');
    const value = record.server ? await api(`/api/v1/actions/${record.id}/resolve`, { printerId, confirmed: true, note: note.input.value }) :
      await api(`/api/v1/actions/${record.id}/resolve-missing`, { target: record.target, action: record.action, expectedJobId: record.expectedJobId, confirmed: true, note: note.input.value });
    controls.adopt([value]); closeEditor(); renderActions(); renderFleet();
  });
}

let editorSubmit;
function openEditor(title, submit, fields, handler) { $('#dialog-title').textContent = title; $('#editor-submit').textContent = submit; $('#editor-error').textContent = ''; $('#editor-fields').replaceChildren(...fields); editorSubmit = handler; if (!$('#editor').open) $('#editor').showModal(); }
function closeEditor() { $('#editor').close(); }
$('#editor-close').onclick = closeEditor; $('#editor-cancel').onclick = closeEditor;
$('#editor-form').addEventListener('submit', async event => {
  event.preventDefault(); const submit = $('#editor-submit'); submit.disabled = true; $('#editor-error').textContent = '';
  try { await editorSubmit(); } catch (e) { $('#editor-error').textContent = e.message; } finally { submit.disabled = false; }
});
function field(label, name, options = {}) {
  const wrap = node('label', 'field', label), input = node(options.textarea ? 'textarea' : options.choices ? 'select' : 'input'); input.name = name;
  if (options.choices) for (const choice of options.choices) { const o = node('option', '', choice.label); o.value = choice.value; input.append(o); }
  for (const [key, value] of Object.entries(options)) if (!['textarea', 'choices'].includes(key)) input[key] = value;
  wrap.append(input); return { wrap, input };
}
function checkbox(label) { const wrap = node('label', 'check'), input = node('input'); input.type = 'checkbox'; wrap.append(input, node('span', '', label)); return { wrap, input }; }
function formFields(definitions, values = {}) {
  const fields = Object.fromEntries(definitions.map(([id, label, options]) => [id, field(label, id, { required: true, ...options, value: values[id] ?? options?.value ?? '' })]));
  return { fields, nodes: Object.values(fields).map(f => f.wrap), value: id => fields[id].input.value };
}
function row(title, detail, action) { const r = node('div', 'list-row'), text = node('div'); text.append(node('strong', '', title), node('small', '', detail)); r.append(text); if (action) r.append(action); return r; }
function renderMaterials() {
  $('#inventory-summary').replaceChildren();
  if (metadataError) $('#inventory-summary').append(node('p', 'error', `Inventory unavailable: ${metadataError}`));
  else $('#inventory-summary').append(node('p', 'inventory-count', spools.length ? `${spools.length} rolls · ${new Set(spools.map(s=>s.filament?.id)).size} colors in Spoolman` : 'No rolls yet · review a label to begin'));
  $('#assignment-list').replaceChildren();
  for (const a of currentAssignments()) $('#assignment-list').append(row(`${a.printerId} · ${a.slot} → spool #${a.spoolId}`, `${a.source==='cfsync'?'CFSync · '+a.state:'Operator confirmed '+time(a.confirmedAt)}`, a.source==='cfsync'?link('Manage ↗','/cfsync/'):button('Change', () => assignmentEditor(a))));
  const recordCount = currentAssignments().length + imports.length;
  $('#material-records').hidden = recordCount === 0;
  $('#material-record-count').textContent = String(recordCount);
  $('#import-list').replaceChildren();
  for (const r of imports) $('#import-list').append(row(`${r.preview.label.maker} · ${r.preview.filament.name}`, `${r.preview.spoolReference} · ${words(r.status)}${r.spoolId ? ` · spool #${r.spoolId}` : ''}`, button('Review', () => importPreview(r))));
}
function assignmentEditor(existing) {
  if(integration.cfsyncConfigured){location.assign('/cfsync/');return;}
  if (!fleet) return toast('Wait for the printer list to load.');
  if (inventoryError || inventoryRevision !== integration.spoolmanRevision || assignments.spoolmanRevision !== inventoryRevision) return toast('Refresh inventory before assigning a spool.');
  const locations = fleet.printers.flatMap(p => p.cfs.flatMap(b => b.slots.map(s => ({ value: `${p.id}:${s.designation}`, label: `${p.name} · ${s.designation} · ${s.material ?? 'unknown material'}` }))));
  if (existing && !locations.some(l => l.value === `${existing.printerId}:${existing.slot}`)) locations.push({ value: `${existing.printerId}:${existing.slot}`, label: `${existing.printerId} · ${existing.slot} (disconnected)` });
  const loc = field('Physical location', 'location', { choices: locations });
  if (existing) loc.input.value = `${existing.printerId}:${existing.slot}`;
  const spool = field('Spoolman identity', 'spool', { choices: [{ value: '', label: 'Clear association' }, ...spools.filter(s => !s.archived).map(s => ({ value: String(s.id), label: `#${s.id} · ${s.filament?.vendor?.name ?? ''} ${s.filament?.name ?? ''}` }))] });
  if (existing) spool.input.value = String(existing.spoolId);
  const check = checkbox('I physically verified this spool and slot. A recorded assignment does not load filament or change printer settings.');
  const id = requestId(), baseVersion = assignments.version, expectedSpoolmanVersion = inventoryRevision;
  openEditor('Assign a physical spool', 'Save assignment', [node('p', 'dialog-note', 'Choose the actual physical spool. Assigning it here moves its recorded location; CFS RFID alone does not establish spool identity.'), loc.wrap, spool.wrap, check.wrap], async () => {
    if (!check.input.checked) throw new Error('Confirm the physical position first.');
    const [printerId, slot] = loc.input.value.split(':');
    await api('/api/v1/assignments', { id, printerId, slot, expectedSpoolmanVersion, spoolId: spool.input.value ? Number(spool.input.value) : null, baseVersion, confirmed: true });
    assignments = await api('/api/v1/assignments');
    closeEditor(); renderMaterials(); renderFleet(); toast('Physical assignment recorded');
  });
}
function importEditor() {
  const expectedSpoolmanVersion = integration.spoolmanRevision;
  const f = formFields([
    ['reference', 'Unique physical spool reference', { maxLength: 128, placeholder: 'Your label ID or unique spool name' }], ['maker', 'Maker', { maxLength: 64 }], ['material', 'Material', { maxLength: 40 }], ['color', 'Color name', { maxLength: 24 }],
    ['hex', 'Color hex (optional)', { required: false, placeholder: '#AABBCC', pattern: '#?[a-fA-F0-9]{6}' }], ['diameter', 'Diameter (mm)', { type: 'number', min: '.01', max: '10', step: '.01' }],
    ['density', 'Density (g/cm³)', { type: 'number', min: '.01', max: '30', step: '.001' }], ['densitySource', 'Density source', { maxLength: 200, placeholder: 'Manufacturer datasheet or material profile' }],
    ['initial', 'Original net filament mass (g)', { type: 'number', min: '.01', max: '100000', step: '.01' }], ['remaining', 'Current remaining filament mass (g)', { type: 'number', min: '0', max: '100000', step: '.01' }], ['notes', 'Reviewed label notes (optional)', { textarea: true, required: false, maxLength: 400 }]
  ]);
  const check = checkbox('I reviewed the label, physical spool identity, measurements and density source. Remaining mass is not a CFS percentage.');
  const id = requestId();
  openEditor('Review a spool label', 'Save preview', [node('p', 'dialog-note', 'Use details from your Spoolmark label. Nothing is added to Spoolman until you review the saved preview.'), ...f.nodes, check.wrap], async () => {
    if (!check.input.checked) throw new Error('Review and confirm the values first.');
    const result = await api('/api/v1/imports/preview', { expectedSpoolmanVersion, schemaVersion: 1, source: 'spoolmark', id, reviewed: true, spoolReference: f.value('reference'), colorHex: f.value('hex') || null,
      label: { maker: f.value('maker'), material: f.value('material'), color: f.value('color'), notes: f.value('notes') },
      measurements: { diameterMm: Number(f.value('diameter')), densityGcm3: Number(f.value('density')), densitySource: f.value('densitySource'), initialWeightG: Number(f.value('initial')), remainingWeightG: Number(f.value('remaining')) } });
    imports = [result, ...imports.filter(r => r.id !== result.id)]; renderMaterials(); importPreview(result);
  });
}
function importPreview(record) {
  const p = record.preview, preview = node('pre', '', `${p.spoolReference}\n${p.label.maker} · ${p.filament.name}\n${p.measurements.diameterMm} mm · ${p.measurements.densityGcm3} g/cm³\nDensity: ${p.measurements.densitySource}\nOriginal: ${p.measurements.initialWeightG} g\nRemaining: ${p.measurements.remainingWeightG} g\n\n${p.filament.comment}\n\nStatus: ${words(record.status)}${record.detail ? '\n' + record.detail : ''}`);
  const check = checkbox('Add this reviewed physical spool to Spoolman using the saved preview.');
  const complete = record.status === 'complete', enabled = integration.inventoryWritesEnabled;
  openEditor('Saved spool preview', complete || !enabled ? 'Close preview' : record.status === 'outcome_unknown' ? 'Reconcile saved import' : 'Add to Spoolman', [preview,
    node('p', 'dialog-note', complete ? `Created spool #${record.spoolId}. Assign its physical slot separately.` : !enabled ? 'Spoolman writes are disabled in service configuration. This preview is saved.' : 'An uncertain prior write is checked by its unique marker before any later step. It is never blindly replayed.'), ...(complete || !enabled ? [] : [check.wrap])], async () => {
    if (complete || !enabled) return closeEditor();
    if (!check.input.checked) throw new Error('Confirm the saved preview first.');
    const result = await api(`/api/v1/imports/${record.id}/commit`, { confirmed: true, expectedSpoolmanVersion: record.spoolmanRevision });
    imports = imports.map(r => r.id === result.id ? result : r); renderMaterials(); importPreview(result);
  });
}
function renderProjects() {
  $('#project-list').replaceChildren();
  if (!projects.length) $('#project-list').append(node('p', 'empty', 'No project records yet. Add a model revision when you are ready.'));
  for (const p of projects) {
    const panel = node('article', 'panel'), head = node('div', 'panel-heading'); head.append(node('h3', '', p.title), node('span', 'tag', words(p.analysisStatus)));
    panel.append(head, node('p', 'muted', `${p.revision} · ${p.material} · ${p.orientation}`), node('p', 'small', p.model.filename), node('p', 'muted small', `Model ${p.model.sha256.slice(0, 16)}… · version ${p.version}`), button('Review project', () => projectEditor(p))); $('#project-list').append(panel);
  }
}
async function fingerprint(file) {
  if (!file) return null;
  if (!crypto.subtle) throw new Error('File fingerprinting requires localhost or HTTPS. Enter a SHA-256 calculated on your computer.');
  if (file.size > 100 * 1024 * 1024) throw new Error('For files over 100 MB, calculate SHA-256 locally and enter the filename and hash.');
  const hash = await crypto.subtle.digest('SHA-256', await file.arrayBuffer());
  return { filename: file.name, sha256: [...new Uint8Array(hash)].map(b => b.toString(16).padStart(2, '0')).join('') };
}
function projectEditor(current) {
  const f = formFields([
    ['title', 'Project title', { maxLength: 200 }], ['url', 'Project URL', { type: 'url' }], ['revision', 'Revision', { maxLength: 200 }], ['material', 'Material', { maxLength: 1000 }], ['orientation', 'Print orientation', { maxLength: 1000 }],
    ['modelName', 'Model filename', { maxLength: 255 }], ['modelHash', 'Model SHA-256', { pattern: '[a-fA-F0-9]{64}' }], ['reportName', 'Report filename (optional)', { required: false, maxLength: 255 }], ['reportHash', 'Report SHA-256 (optional)', { required: false, pattern: '[a-fA-F0-9]{64}' }],
    ['reportModelHash', 'Model SHA-256 actually analyzed by the report', { required: false, pattern: '[a-fA-F0-9]{64}' }], ['note', 'Review note', { textarea: true, required: false, maxLength: 2000 }]
  ], { title: current?.title, url: current?.projectUrl ?? 'https://github.com/77kmp9jr2f-jpg/openFEA', revision: current?.revision, material: current?.material, orientation: current?.orientation,
    modelName: current?.model.filename, modelHash: current?.model.sha256, reportName: current?.report?.filename, reportHash: current?.report?.sha256, reportModelHash: current?.report?.modelSha256, note: current?.review.note });
  const modelFile = field('Fingerprint a model file locally (optional)', 'modelFile', { type: 'file' }), reportFile = field('Fingerprint a report locally (optional)', 'reportFile', { type: 'file' });
  modelFile.input.disabled = reportFile.input.disabled = !crypto.subtle;
  for (const [file, prefix] of [[modelFile, 'model'], [reportFile, 'report']]) file.input.addEventListener('change', async () => {
    try { const result = await fingerprint(file.input.files[0]); if (result) { f.fields[`${prefix}Name`].input.value = result.filename; f.fields[`${prefix}Hash`].input.value = result.sha256; } } catch (e) { $('#editor-error').textContent = e.message; }
  });
  const reviewed = checkbox('I explicitly reviewed this report for this exact model, revision, material and orientation.');
  const id = current?.id ?? requestId();
  openEditor(current ? 'Review project record' : 'Add a project record', 'Save project', [node('p', 'dialog-note', `Files stay on your device. Only filenames and hashes are stored. Enter the report’s actual analyzed model hash.${crypto.subtle ? '' : ' On HTTP Simulated datas, calculate SHA-256 on your computer and enter it below; automatic file fingerprinting is available on the Print room host at localhost.'}`), modelFile.wrap, reportFile.wrap, ...f.nodes, reviewed.wrap], async () => {
    const result = await api('/api/v1/projects', { baseVersion: current?.version ?? 0, confirmReview: reviewed.input.checked, handoff: { schemaVersion: 1, id, title: f.value('title'), projectUrl: f.value('url'), revision: f.value('revision'), material: f.value('material'), orientation: f.value('orientation'),
      model: { filename: f.value('modelName'), sha256: f.value('modelHash') }, report: f.value('reportName') || f.value('reportHash') || f.value('reportModelHash') ? { filename: f.value('reportName'), sha256: f.value('reportHash'), modelSha256: f.value('reportModelHash') } : null,
      review: { status: reviewed.input.checked ? 'reviewed' : 'needs_review', note: f.value('note') } } });
    projects = [result, ...projects.filter(p => p.id !== id)]; closeEditor(); renderProjects(); toast('Project revision saved');
  });
}

async function refreshFleet() {
  try { fleet = await api('/api/v1/fleet'); fleetError = null; }
  catch (e) {
    fleetError = e.message;
    $('#service-message').textContent = `Connection failed: ${e.message}`;
    $('#service-message').dataset.warning = 'true';
    $('#connection').textContent = 'Service unavailable';
    $('#connection').dataset.state = 'offline';
    $('#room-mark').textContent = fleet ? `${fleet.printers.length} printer${fleet.printers.length === 1 ? '' : 's'}` : 'Unavailable';
    if (!fleet) showSkeletons();
  }
  renderFleet();
}
async function refreshActions() { try { await controls.refresh(); actionError = null; } catch (e) { actionError = e.message; } renderActions(); renderFleet(); }
async function refreshMaterials() {
  const results = await Promise.allSettled([api('/api/v1/integrations'), loadSpools(api), api('/api/v1/assignments'), api('/api/v1/imports'), api('/api/v1/projects')]);
  const [i, s, a, im, p] = results; metadataError = results.find(r => r.status === 'rejected')?.reason.message ?? null;
  if (i.status === 'fulfilled') {
    if (integration.spoolmanRevision !== i.value.spoolmanRevision) { spools = []; inventoryObservedAt = null; inventoryRevision = null; cfsyncState = null; }
    integration = i.value;
    if (integration.spoolmanUrl) { const u = new URL(integration.spoolmanUrl); if (u.hostname === 'host.docker.internal') u.hostname = location.hostname; integration.spoolmanUrl = u.href; }
    document.querySelectorAll('[data-spoolman-link]').forEach(a => { a.hidden = !integration.spoolmanUrl; if (integration.spoolmanUrl) a.href = integration.spoolmanUrl; else a.removeAttribute('href'); });
  }
  if (s.status === 'fulfilled' && s.value.spoolmanRevision === integration.spoolmanRevision) { inventoryRevision = s.value.spoolmanRevision; spools = s.value.spools; inventoryObservedAt=s.value.observedAt; inventoryError=null;integration.moreSpools=false; } else { inventoryError=s.status === 'rejected' ? s.reason.message : 'Spoolman connection changed. Refresh inventory.'; }
  if (a.status === 'fulfilled') assignments = a.value;
  if (im.status === 'fulfilled') imports = im.value.imports;
  if (p.status === 'fulfilled') projects = p.value.projects;
  renderMaterials(); renderProjects(); renderFleet();renderLibrary();await refreshCfsync();
}

function renderLibrary(){libraryView.update(spools,{observedAt:inventoryObservedAt,error:inventoryError,assignments:currentAssignments(),spoolmanUrl:integration.spoolmanUrl});}
async function refreshCfsync() {
  document.querySelectorAll('[data-cfsync-link]').forEach(a=>a.hidden=!integration.cfsyncConfigured);
  $('#assign-open').hidden=!!integration.cfsyncConfigured;$('#cfsync-status').hidden=!integration.cfsyncConfigured;
  if(!integration.cfsyncConfigured)return;
  try {cfsyncState=await api('/api/v1/cfsync');cfsyncError=null;}catch(e){cfsyncState=null;cfsyncError=e.message;}
  $('#cfsync-status').textContent=cfsyncError?'CFSync unavailable · '+cfsyncError:
    cfsyncState.printers.map(p=>(fleet?.printers.find(f=>f.id===p.id)?.name??p.id)+' '+p.presentSlots+' loaded'+(p.state==='fresh'?'':' · '+p.state)).join(' · ')+' · '+cfsyncState.assignments.length+' linked in CFSync';
  $('#cfsync-status').dataset.warning=String(!!cfsyncError);
  renderMaterials();renderFleet();renderLibrary();
}

$('#fleet-query').oninput = renderFleet;
$('#refresh-actions').onclick = refreshActions; $('#refresh-materials').onclick = refreshMaterials;
$('#focus-toggle').onclick = () => {
  const focused = document.body.classList.toggle('focus-view');
  $('#focus-toggle').setAttribute('aria-pressed', focused); $('#focus-toggle').textContent = focused ? 'Full view' : 'Focus view';
  document.getElementById('printers').scrollIntoView({ block: 'start' });
};
$('#assign-open').onclick = () => assignmentEditor(); $('#import-open').onclick = importEditor; $('#project-open').onclick = () => projectEditor();
$('#pairing-form').onsubmit = async e => {
  e.preventDefault(); $('#pairing-submit').disabled = true;
  try { await browserSession($('#pairing-code').value.trim()); $('#pairing-code').value = ''; await Promise.all([refreshFleet(), refreshActions(), refreshMaterials()]); }
  catch (error) { $('#pairing-error').textContent = error.message; }
  finally { $('#pairing-submit').disabled = false; }
};
$('#pair-device').onclick = async () => {
  $('#pair-device').disabled = true;
  try {
    const result = await api('/api/pairing/create', {});
    openEditor('Pair a LAN browser', 'Done', [node('p', 'dialog-note', `On your other device, open ${result.lanUrl} and enter this code. It expires at ${time(result.expiresAt)} and works once.`), node('p', 'pair-code', result.code), node('p', 'dialog-note', 'This grants access to your Print room. Share it only with someone who should have access.')], async () => closeEditor());
  } catch (error) { toast(error.message); } finally { $('#pair-device').disabled = false; }
};
async function poll(fn, delay) { if (!pairingRequired) await fn(); if (!stopping) { const timer = setTimeout(() => { timers.delete(timer); poll(fn, delay); }, delay); timers.add(timer); } }
let stopping = false; const timers = new Set();
const navLinks = [...document.querySelectorAll('nav a[href^="#"]')];
const navSections = navLinks.map(a => document.querySelector(a.getAttribute('href'))).filter(Boolean);
function spyNav() {
  if ($('#workspace')?.hidden) return;
  const mark = window.scrollY + 180;
  let current = navSections[0];
  for (const section of navSections) if (section.offsetTop <= mark) current = section;
  for (const a of navLinks) {
    if (a.getAttribute('href') === '#' + current?.id) a.setAttribute('aria-current', 'page');
    else a.removeAttribute('aria-current');
  }
}
window.addEventListener('scroll', spyNav, { passive: true });
window.addEventListener('hashchange', spyNav);
spyNav();
showSkeletons();
poll(refreshFleet, 5000); poll(refreshActions, 5000); poll(refreshMaterials, 30000); poll(refreshCfsync, 5000);
const ageTimer = setInterval(renderFleet, 1000);
window.addEventListener('pagehide', () => { stopping = true; timers.forEach(clearTimeout); clearInterval(ageTimer); cameraPool.close(); });
window.addEventListener('pageshow', e => { if (e.persisted) window.location.reload(); });
