import { readFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { parseConfig } from './config.mjs';
import { PrinterTelemetry } from './telemetry.mjs';
import { Collectors } from './collectors.mjs';
import { Store } from './store.mjs';
import { CommandService } from './commands.mjs';
import { createApiServer } from './server.mjs';
import { ProjectService } from './projects.mjs';
import { AssignmentService } from './assignments.mjs';
import { InventoryService } from './inventory.mjs';
import { SpoolmanClient } from './spoolman.mjs';
import { SpoolmanSettings } from './spoolman-settings.mjs';
import { drainAndClose } from './shutdown.mjs';
import { fileURLToPath } from 'node:url';
import { LocalBrowser, BrowserPairing } from './local-browser.mjs';
import { CameraProxy } from './camera-proxy.mjs';
import { CfsyncBridge } from './cfsync.mjs';
import { PrinterRegistry } from './printer-registry.mjs';
import { PrinterDiscovery } from './discovery.mjs';
import { PrinterSettings } from './printer-settings.mjs';
import { reconcileFleet } from './fleet.mjs';
import { CommandError } from './commands.mjs';

process.umask(0o077);
const configPath = process.env.PRINT_CONFIG ?? '/config/printers.json';
const token = readFileSync(process.env.PRINT_TOKEN_FILE ?? '/run/secrets/companion_token', 'utf8').trim();
const config = parseConfig(JSON.parse(readFileSync(configPath, 'utf8')), token);
const dataDir = process.env.PRINT_DATA_DIR ?? '/data';
mkdirSync(dataDir, { recursive: true, mode: 0o700 });
const store = new Store(join(dataDir, 'print-companion.sqlite'));
const registry = new PrinterRegistry({ store, initialPrinters: config.printerProfiles });
const printers = registry.runtime();
const telemetry = new Map(printers.map(p => [p.id, new PrinterTelemetry(p)]));
const collectors = new Collectors(printers, telemetry);
const commands = new CommandService({ printers, store, telemetry });
const spoolman = config.spoolman ? new SpoolmanClient(config.spoolman) : null;
const projects = new ProjectService(store);
const assignments = new AssignmentService({ store, telemetry, spoolman });
const inventory = new InventoryService({ store, spoolman });
const publicPort = Number(process.env.PRINT_PUBLIC_PORT ?? 7988);
if (!Number.isInteger(publicPort) || publicPort < 1 || publicPort > 65535) throw new Error('Invalid public port');
const browserOptions = { port: publicPort, assetDir: fileURLToPath(new URL('../web/', import.meta.url)), lanHost: config.lanHost, pairing: new BrowserPairing(), lanAccess: process.env.PRINT_LAN_ACCESS ?? 'paired' };
const localBrowser = new LocalBrowser(browserOptions);
const cameras = new CameraProxy({ base: process.env.PRINT_CAMERA_RELAY ?? 'http://camera:1984', printers });
const cfsync=process.env.PRINT_CFSYNC_ENABLED==='true' ? new CfsyncBridge({printerIds:config.printers.map(p=>p.id)}) : null;
const spoolmanSettings = new SpoolmanSettings({ store, initialConnection: config.spoolman, inventory, assignments, cfsync });
registry.beforeChange = () => { if (commands.pending.size) throw new CommandError('Wait for active command processing before changing printer configuration.', 409); };
registry.onChange = next => reconcileFleet(next, { telemetry, collectors, commands, cameras, cfsync, cfsyncSeed: config.printers });
registry.onChange(printers);
const discovery = new PrinterDiscovery();
const settings = new PrinterSettings({ registry, discovery, spoolmanSettings, lanHost: config.lanHost, publicPort, controlsEnabled: config.controlsEnabled, inventoryWritesEnabled: config.inventoryWritesEnabled, cfsyncConfigured: !!cfsync });
const apiOptions = { token, telemetry, commands, store, projects, assignments, inventory, spoolman, spoolmanSettings, cameras, cfsync, settings,
  controlsEnabled: config.controlsEnabled, inventoryWritesEnabled: config.inventoryWritesEnabled };
const server = createApiServer({ ...apiOptions, localBrowser });
const lanServer = config.lanHost ? createApiServer({ ...apiOptions, allowBearer: false, localBrowser: new LocalBrowser({ ...browserOptions, access: 'lan' }) }) : null;
const port = Number(process.env.PORT ?? 8080);
if (!Number.isInteger(port) || port < 1 || port > 65535) throw new Error('Invalid listening port');
if (port === 8081 && lanServer) throw new Error('Local and LAN listener ports must differ');
if (lanServer) lanServer.listen(8081, '0.0.0.0', () => console.log(JSON.stringify({ event: 'lan-started', host: config.lanHost, port: 8081 })));
server.listen(port, '0.0.0.0', () => {
  console.log(JSON.stringify({ event: 'started', port, printers: printers.map(p => p.id), controlsEnabled: config.controlsEnabled }));
  collectors.start();
});
let closing = false;
async function stop() {
  if (closing) return;
  closing = true;
  const deadline = setTimeout(() => process.exit(1), 10_000);
  deadline.unref();
  await discovery.close();
  await drainAndClose({ servers: [server, lanServer].filter(Boolean), collectors, commands, inventory, store });
  clearTimeout(deadline);
}
process.on('SIGTERM', stop);
process.on('SIGINT', stop);
